app:
  name: "E-Commerce Payment System"
  version: "1.0.0"
  environment: "development"

database:
  driver: "sqlite3"
  path: "data/ecommerce.db"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

logging:
  level: "error"
  format: "console"
  output: "file"
  file_path: "logs/app.log"

payment:
  timeout: "30s"
  retry_attempts: 3
  retry_delay: "1s"
  
  credit_card:
    enabled: true
    min_amount: 1.00
    max_amount: 10000.00
    
  paypal:
    enabled: true
    min_amount: 1.00
    max_amount: 5000.00
    
  crypto:
    enabled: true
    min_amount: 10.00
    max_amount: 50000.00
    supported_currencies:
      - "BTC"
      - "ETH"
      - "USDT"

decorators:
  discount:
    enabled: true
    max_percentage: 50.0
    max_fixed_amount: 500.00
    
  cashback:
    enabled: true
    tier1_threshold: 100.00
    tier1_percentage: 5.0
    tier2_percentage: 10.0
    
  fraud_detection:
    enabled: true
    max_risk_score: 80
    velocity_check_window: "1h"
    max_transactions_per_window: 5
    
  tax:
    enabled: true
    default_rate: 8.5
    rates:
      CA: 9.5
      NY: 8.875
      TX: 6.25
      FL: 6.0
      
  loyalty_points:
    enabled: true
    points_to_currency_ratio: 100
    max_redemption_percentage: 50.0

notifications:
  email:
    enabled: true
    smtp_host: "smtp.example.com"
    smtp_port: 587
    from_address: "noreply@ecommerce.com"
    worker_pool_size: 5
    
  sms:
    enabled: true
    provider: "twilio"
    rate_limit: 10
    
  webhook:
    enabled: true
    timeout: "10s"
    retry_attempts: 3
    
  audit:
    enabled: true
    log_path: "logs/audit.log"

metrics:
  enabled: true
  export_interval: "1m"

cli:
  page_size: 10
  timeout: "5m"
  theme: "default"
